<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FluxMq.Components\FluxMq.Components.csproj" />
    <ProjectReference Include="..\FluxMq.Scenarios\FluxMq.Scenarios.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluxFlow.Components.Control" Version="0.1.0-alpha.1" />
    <PackageReference Include="FluxFlow.Components.Http" Version="0.1.0-alpha.1" />
    <PackageReference Include="FluxFlow.Components.Mapping" Version="0.1.0-alpha.1" />
    <PackageReference Include="FluxFlow.Components.Payloads" Version="0.1.0-alpha.1" />
    <PackageReference Include="FluxFlow.Components.Serialization" Version="0.1.0-alpha.1" />
    <PackageReference Include="FluxFlow.Components.Timers" Version="0.4.1-alpha.1" />
    <PackageReference Include="FluxFlow.Engine" Version="0.5.0-alpha.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.7" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
