<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FluxMq.Components\FluxMq.Components.csproj" />
    <ProjectReference Include="..\FluxMq.Scenarios\FluxMq.Scenarios.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluxFlow.Engine" Version="0.3.0-alpha.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.7" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
