<Project>
  <PropertyGroup>
    <FluxFlowEngineVersion>1.0.0</FluxFlowEngineVersion>
    <FluxFlowComponentsDesignerVersion>1.0.0</FluxFlowComponentsDesignerVersion>
    <FluxFlowComponentsAssertionsVersion>0.2.0-alpha.1</FluxFlowComponentsAssertionsVersion>
    <FluxFlowComponentsControlVersion>0.3.0-alpha.1</FluxFlowComponentsControlVersion>
    <FluxFlowComponentsFileSystemVersion>0.5.0-alpha.1</FluxFlowComponentsFileSystemVersion>
    <FluxFlowComponentsHttpVersion>0.2.0-alpha.1</FluxFlowComponentsHttpVersion>
    <FluxFlowComponentsMappingVersion>0.2.0-alpha.1</FluxFlowComponentsMappingVersion>
    <FluxFlowComponentsMetricsVersion>0.2.0-alpha.1</FluxFlowComponentsMetricsVersion>
    <FluxFlowComponentsMqttVersion>0.5.0-alpha.1</FluxFlowComponentsMqttVersion>
    <FluxFlowComponentsObservabilityVersion>0.3.0-alpha.1</FluxFlowComponentsObservabilityVersion>
    <FluxFlowComponentsPayloadsVersion>0.1.1-alpha.1</FluxFlowComponentsPayloadsVersion>
    <FluxFlowComponentsRoutingVersion>0.10.0-alpha.1</FluxFlowComponentsRoutingVersion>
    <FluxFlowComponentsSerializationVersion>0.1.1-alpha.1</FluxFlowComponentsSerializationVersion>
    <FluxFlowComponentsSecretsVersion>0.2.0-alpha.1</FluxFlowComponentsSecretsVersion>
    <FluxFlowComponentsSessionsVersion>0.3.0-alpha.1</FluxFlowComponentsSessionsVersion>
    <FluxFlowComponentsSourcesVersion>0.2.0-alpha.1</FluxFlowComponentsSourcesVersion>
    <FluxFlowComponentsStateVersion>0.3.0-alpha.1</FluxFlowComponentsStateVersion>
    <FluxFlowComponentsStorageVersion>0.3.0-alpha.1</FluxFlowComponentsStorageVersion>
    <FluxFlowComponentsStorageFileSystemVersion>0.2.0-alpha.1</FluxFlowComponentsStorageFileSystemVersion>
    <FluxFlowComponentsTimersVersion>0.5.0-alpha.1</FluxFlowComponentsTimersVersion>
    <FluxFlowComponentsValidationVersion>0.2.0-alpha.1</FluxFlowComponentsValidationVersion>
    <FluxFlowSourceRoot Condition="'$(FluxFlowSourceRoot)' == ''">$(MSBuildThisFileDirectory)..\FluxFlow\</FluxFlowSourceRoot>
    <UseFluxFlowSourceReferences Condition="'$(UseFluxFlowSourceReferences)' == ''">false</UseFluxFlowSourceReferences>
  </PropertyGroup>
</Project>
