<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FluxMq.Core\FluxMq.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluxFlow.Components.Control" Version="0.1.0-alpha.1" />
    <PackageReference Include="FluxFlow.Components.FileSystem" Version="0.1.0-alpha.1" />
    <PackageReference Include="FluxFlow.Components.Metrics" Version="0.1.0-alpha.1" />
    <PackageReference Include="FluxFlow.Components.Mqtt" Version="0.2.1-alpha.1" />
    <PackageReference Include="FluxFlow.Components.Observability" Version="0.1.0-alpha.1" />
    <PackageReference Include="FluxFlow.Components.Validation" Version="0.1.0-alpha.1" />
    <PackageReference Include="FluxFlow.Engine" Version="0.5.0-alpha.1" />
    <PackageReference Include="LiteDB" Version="5.0.21" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
