<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FluxMq.Core\FluxMq.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DynamicExpresso.Core" Version="2.19.3" />
    <PackageReference Include="Jsonata.Net.Native" Version="3.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
